// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeApi.Infrastructure;

#nullable disable

namespace RecipeApi.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20260407130841_AddRecipeSections")]
    partial class AddRecipeSections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("RecipeCategory", (string)null);
                });

            modelBuilder.Entity("RecipeApi.Features.Recipes.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Group = "Måltidstype",
                            Name = "Frokost"
                        },
                        new
                        {
                            Id = 2,
                            Group = "Måltidstype",
                            Name = "Lunsj"
                        },
                        new
                        {
                            Id = 3,
                            Group = "Måltidstype",
                            Name = "Middag"
                        },
                        new
                        {
                            Id = 4,
                            Group = "Måltidstype",
                            Name = "Dessert"
                        },
                        new
                        {
                            Id = 5,
                            Group = "Måltidstype",
                            Name = "Kveldsmat"
                        },
                        new
                        {
                            Id = 6,
                            Group = "Måltidstype",
                            Name = "Søtbakst"
                        },
                        new
                        {
                            Id = 7,
                            Group = "Måltidstype",
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = 8,
                            Group = "Måltidstype",
                            Name = "Drikke"
                        },
                        new
                        {
                            Id = 9,
                            Group = "Vanskelighetsgrad",
                            Name = "Enkel"
                        },
                        new
                        {
                            Id = 10,
                            Group = "Vanskelighetsgrad",
                            Name = "Middels"
                        },
                        new
                        {
                            Id = 11,
                            Group = "Vanskelighetsgrad",
                            Name = "Avansert"
                        },
                        new
                        {
                            Id = 12,
                            Group = "Tilberedningstid",
                            Name = "Under 15 min"
                        },
                        new
                        {
                            Id = 13,
                            Group = "Tilberedningstid",
                            Name = "Under 30 min"
                        },
                        new
                        {
                            Id = 14,
                            Group = "Tilberedningstid",
                            Name = "Under 1 time"
                        },
                        new
                        {
                            Id = 15,
                            Group = "Tilberedningstid",
                            Name = "Over 1 time"
                        });
                });

            modelBuilder.Entity("RecipeApi.Features.Recipes.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CookTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IngredientSections")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructionSections")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructionSteps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrepTime")
                        .HasColumnType("int");

                    b.Property<int?>("Servings")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookTime = "20 minutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A traditional Italian pasta dish with eggs, cheese, and pancetta",
                            Difficulty = "Medium",
                            ImageUrl = "/api/placeholder/300/200",
                            IngredientSections = "[]",
                            Ingredients = "[]",
                            InstructionSections = "[]",
                            InstructionSteps = "[]",
                            Title = "Classic Spaghetti Carbonara",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CookTime = "45 minutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Creamy and flavorful Indian curry with tender chicken pieces",
                            Difficulty = "Medium",
                            ImageUrl = "/api/placeholder/300/200",
                            IngredientSections = "[]",
                            Ingredients = "[]",
                            InstructionSections = "[]",
                            InstructionSteps = "[]",
                            Title = "Chicken Tikka Masala",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CookTime = "25 minutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft and chewy homemade cookies with chocolate chips",
                            Difficulty = "Easy",
                            ImageUrl = "/api/placeholder/300/200",
                            IngredientSections = "[]",
                            Ingredients = "[]",
                            InstructionSections = "[]",
                            InstructionSteps = "[]",
                            Title = "Chocolate Chip Cookies",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CookTime = "15 minutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh romaine lettuce with homemade caesar dressing and croutons",
                            Difficulty = "Easy",
                            ImageUrl = "/api/placeholder/300/200",
                            IngredientSections = "[]",
                            Ingredients = "[]",
                            InstructionSections = "[]",
                            InstructionSteps = "[]",
                            Title = "Caesar Salad",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.HasOne("RecipeApi.Features.Recipes.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeApi.Features.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
