// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeApi.Infrastructure;

#nullable disable

namespace RecipeApi.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20260817112155_AddRecipeShare")]
    partial class AddRecipeShare
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("RecipeCategory", (string)null);
                });

            modelBuilder.Entity("RecipeApi.Features.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RecipeApi.Features.FeaturePlanner.FeatureCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("ColumnId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UiSketch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.ToTable("FeatureCards");

                    b.HasDiscriminator<string>("CardType").HasValue("FeatureCard");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RecipeApi.Features.FeaturePlanner.FeatureColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FeatureColumns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "New",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Planned",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "In Progress",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Done",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("RecipeApi.Features.Groups.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MealPlanEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("RecipeApi.Features.Groups.GroupMember", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("RecipeApi.Features.HeftyMesterskapet.HeftyMesterskapetCompetition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("NineKampCompetitions", (string)null);
                });

            modelBuilder.Entity("RecipeApi.Features.Matkasse.MatkasseRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beskrivelse")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Leverandor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("UkeStart")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "UkeStart");

                    b.ToTable("MatkasseRecipes");
                });

            modelBuilder.Entity("RecipeApi.Features.MealPlans.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomNote")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CustomTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("MatkasseRecipeId")
                        .HasColumnType("int");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MatkasseRecipeId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("GroupId", "Date");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("RecipeApi.Features.Recipes.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Group = "Måltidstype",
                            Name = "Frokost"
                        },
                        new
                        {
                            Id = 2,
                            Group = "Måltidstype",
                            Name = "Lunsj"
                        },
                        new
                        {
                            Id = 3,
                            Group = "Måltidstype",
                            Name = "Middag"
                        },
                        new
                        {
                            Id = 4,
                            Group = "Måltidstype",
                            Name = "Dessert"
                        },
                        new
                        {
                            Id = 5,
                            Group = "Måltidstype",
                            Name = "Kveldsmat"
                        },
                        new
                        {
                            Id = 6,
                            Group = "Måltidstype",
                            Name = "Søtbakst"
                        },
                        new
                        {
                            Id = 7,
                            Group = "Måltidstype",
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = 8,
                            Group = "Måltidstype",
                            Name = "Drikke"
                        },
                        new
                        {
                            Id = 9,
                            Group = "Vanskelighetsgrad",
                            Name = "Enkel"
                        },
                        new
                        {
                            Id = 10,
                            Group = "Vanskelighetsgrad",
                            Name = "Middels"
                        },
                        new
                        {
                            Id = 11,
                            Group = "Vanskelighetsgrad",
                            Name = "Avansert"
                        },
                        new
                        {
                            Id = 12,
                            Group = "Tilberedningstid",
                            Name = "Under 15 min"
                        },
                        new
                        {
                            Id = 13,
                            Group = "Tilberedningstid",
                            Name = "Under 30 min"
                        },
                        new
                        {
                            Id = 14,
                            Group = "Tilberedningstid",
                            Name = "Under 1 time"
                        },
                        new
                        {
                            Id = 15,
                            Group = "Tilberedningstid",
                            Name = "Over 1 time"
                        },
                        new
                        {
                            Id = 16,
                            Group = "Måltidstype",
                            Name = "Tilbehør"
                        });
                });

            modelBuilder.Entity("RecipeApi.Features.Recipes.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CookTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomUnit")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IngredientSections")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructionSections")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructionSteps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PrepTime")
                        .HasColumnType("int");

                    b.Property<string>("QuantityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("Servings")
                        .HasColumnType("float");

                    b.Property<string>("SourceImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tips")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Public");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookTime = "20 minutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A traditional Italian pasta dish with eggs, cheese, and pancetta",
                            ImageUrl = "/api/placeholder/300/200",
                            IngredientSections = "[]",
                            Ingredients = "[]",
                            InstructionSections = "[]",
                            InstructionSteps = "[]",
                            QuantityType = "porsjoner",
                            Tips = "[]",
                            Title = "Classic Spaghetti Carbonara",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Visibility = "Public"
                        },
                        new
                        {
                            Id = 2,
                            CookTime = "45 minutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Creamy and flavorful Indian curry with tender chicken pieces",
                            ImageUrl = "/api/placeholder/300/200",
                            IngredientSections = "[]",
                            Ingredients = "[]",
                            InstructionSections = "[]",
                            InstructionSteps = "[]",
                            QuantityType = "porsjoner",
                            Tips = "[]",
                            Title = "Chicken Tikka Masala",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Visibility = "Public"
                        },
                        new
                        {
                            Id = 3,
                            CookTime = "25 minutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft and chewy homemade cookies with chocolate chips",
                            ImageUrl = "/api/placeholder/300/200",
                            IngredientSections = "[]",
                            Ingredients = "[]",
                            InstructionSections = "[]",
                            InstructionSteps = "[]",
                            QuantityType = "porsjoner",
                            Tips = "[]",
                            Title = "Chocolate Chip Cookies",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Visibility = "Public"
                        },
                        new
                        {
                            Id = 4,
                            CookTime = "15 minutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh romaine lettuce with homemade caesar dressing and croutons",
                            ImageUrl = "/api/placeholder/300/200",
                            IngredientSections = "[]",
                            Ingredients = "[]",
                            InstructionSections = "[]",
                            InstructionSteps = "[]",
                            QuantityType = "porsjoner",
                            Tips = "[]",
                            Title = "Caesar Salad",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Visibility = "Public"
                        });
                });

            modelBuilder.Entity("RecipeApi.Features.Recipes.RecipeGroup", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("RecipeId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("RecipeGroups");
                });

            modelBuilder.Entity("RecipeApi.Features.Recipes.RecipeLike", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RecipeId", "UserEmail");

                    b.ToTable("RecipeLikes");
                });

            modelBuilder.Entity("RecipeApi.Features.Recipes.RecipeShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId")
                        .IsUnique()
                        .HasFilter("[RevokedAt] IS NULL");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RecipeShares");
                });

            modelBuilder.Entity("RecipeApi.Features.Recipes.RecipeSideDish", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("SideDishRecipeId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("RecipeId", "SideDishRecipeId");

                    b.HasIndex("SideDishRecipeId");

                    b.HasIndex("RecipeId", "SortOrder");

                    b.ToTable("RecipeSideDishes");
                });

            modelBuilder.Entity("RecipeApi.Features.FeaturePlanner.BugCard", b =>
                {
                    b.HasBaseType("RecipeApi.Features.FeaturePlanner.FeatureCard");

                    b.Property<string>("BugUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Bug");
                });

            modelBuilder.Entity("RecipeApi.Features.FeaturePlanner.FeatureOnlyCard", b =>
                {
                    b.HasBaseType("RecipeApi.Features.FeaturePlanner.FeatureCard");

                    b.Property<string>("ApiSketch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenQuestions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutOfScope")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StacksBackend")
                        .HasColumnType("bit");

                    b.Property<bool>("StacksFrontend")
                        .HasColumnType("bit");

                    b.Property<bool>("StacksInfrastructure")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Feature");
                });

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.HasOne("RecipeApi.Features.Recipes.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeApi.Features.Recipes.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeApi.Features.FeaturePlanner.FeatureCard", b =>
                {
                    b.HasOne("RecipeApi.Features.FeaturePlanner.FeatureColumn", "Column")
                        .WithMany("Cards")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");
                });

            modelBuilder.Entity("RecipeApi.Features.Groups.Group", b =>
                {
                    b.HasOne("RecipeApi.Features.Auth.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("RecipeApi.Features.Groups.GroupMember", b =>
                {
                    b.HasOne("RecipeApi.Features.Groups.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeApi.Features.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeApi.Features.Matkasse.MatkasseRecipe", b =>
                {
                    b.HasOne("RecipeApi.Features.Groups.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("RecipeApi.Features.MealPlans.MealPlan", b =>
                {
                    b.HasOne("RecipeApi.Features.Groups.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeApi.Features.Matkasse.MatkasseRecipe", "MatkasseRecipe")
                        .WithMany()
                        .HasForeignKey("MatkasseRecipeId");

                    b.HasOne("RecipeApi.Features.Recipes.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");

                    b.Navigation("MatkasseRecipe");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeApi.Features.Recipes.RecipeGroup", b =>
                {
                    b.HasOne("RecipeApi.Features.Groups.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeApi.Features.Recipes.Recipe", "Recipe")
                        .WithMany("Groups")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeApi.Features.Recipes.RecipeLike", b =>
                {
                    b.HasOne("RecipeApi.Features.Recipes.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeApi.Features.Recipes.RecipeShare", b =>
                {
                    b.HasOne("RecipeApi.Features.Recipes.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeApi.Features.Recipes.RecipeSideDish", b =>
                {
                    b.HasOne("RecipeApi.Features.Recipes.Recipe", "Recipe")
                        .WithMany("SideDishes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeApi.Features.Recipes.Recipe", "SideDishRecipe")
                        .WithMany("UsedAsSideDishIn")
                        .HasForeignKey("SideDishRecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("SideDishRecipe");
                });

            modelBuilder.Entity("RecipeApi.Features.FeaturePlanner.FeatureColumn", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("RecipeApi.Features.Groups.Group", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("RecipeApi.Features.Recipes.Recipe", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("SideDishes");

                    b.Navigation("UsedAsSideDishIn");
                });
#pragma warning restore 612, 618
        }
    }
}
